function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
	msg.post(".", "acquire_input_focus")

	self.colName = nil --object with we are coliding
	self.pressed = false
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
	local pos = go.get_position()
	self.colName = ""
	
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
	if message_id == hash("collision_response") then
		self.colName = message.other_id..""
		print (self.colName.."" )
		if self.colName == "[/Printer]" then
			sound.play("/Clicker#CashSound")
			local scaleChanged = vmath.vector3(0.7, 0.7, 0.7)
			go.set_scale(scaleChanged, "/Printer")
			msg.post("/Clicker#Click", "increase_dolars")
			print("entro")
		end
		if self.colName == "[/ButtonBar]" then
			msg.post("/ButtonBar", "CreateBar")
		end

		if self.colName == "[/ButtonFactory]" then
			msg.post("/ButtonFactory#CreateFactory", "CreateFactory")
		end
		if self.colName == "[/ButtonHospital]" then
			msg.post("/ButtonHospital#CreateHospital", "CreateHospital")
		end
		
		msg.post("#collisionobject", "disable")--/cursor#collisionobject
		self.pressed = false;
	end
	
end

function on_input(self, action_id, action)
	if action_id == hash("touch") then
		local pos = vmath.vector3(action.x,action.y,0)
		go.set_position(pos)
		if action.pressed then
			msg.post("#collisionobject", "enable")--/cursor#collisionobject
			self.pressed = true;
		end
		if action.released then
			msg.post("#collisionobject", "disable")--/cursor#collisionobject
			self.pressed = false;
		end

	end
	
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
